chore: change android, ios build script

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -14,11 +14,19 @@ workflows:
           include: true
           source: true
     scripts:
-      - name: Move to menuboss-en directory
-        script: cd menuboss-en
-      - name: Check current directory
+      - name: List directory contents
         script: |
-          echo "Current directory:"
+          echo "Listing contents of /Users/builder/clone:"
+          ls -al
+      - name: Move to menuboss-en directory and check
+        script: |
+          cd menuboss-en || { echo "Failed to change directory"; exit 1; }
+          echo "Changed to directory:"
+          pwd
+      - name: Move to menuboss-en directory using absolute path
+        script: |
+          cd /path/to/menuboss-en
+          echo "Changed to directory:"
           pwd
       - name: Clean Run Build
         script: make run-rebuild
